now using qmulits/moodlehost images from Docker Hub

diff --git a/moodlehost b/moodlehost
--- a/moodlehost
+++ b/moodlehost
@@ -7,6 +7,7 @@
 # v.0.1 - works
 # v.0.2 - allowing cli options to override values
 # v.1.0 - added installer script - GM
+# v.1.1 - allowing to specify path to webroot
 
 usage() { 
 	echo "Usage: $0 [-d <db_host_ip>] [-h] [-m <moodledata_path>] [-p <ip_port>] [-v <php_version> [start][stop][purge]" 1>&2; 
@@ -16,11 +17,12 @@ usage() {
 help() {
 	echo "Usage: $0 [-d <db_host_ip>] [-h] [-m <moodledata_path>] [-p <ip_port>] [-v <php_version> [start][stop][purge]" 1>&2; 
 	echo "available options:"
-	echo "-d <db_host_ip>: set the ip address of the database server (default = 127.0.0.1)"
+	echo "-d <db_host_ip>: set the IP address of the database server (default = 127.0.0.1)"
 	echo "-h this help page"
-	echo "-m <moodledata_path>: set path on host(!) to moodledata (default is ./moodledata)"
+	echo "-m <moodledata>: set path on host(!) to moodledata (default is $PWD/moodledata)"
 	echo "-p <port>: set the port number used by Apache (default=80)"	
 	echo "-v <php_version>: select the PHP version (default=7.3, allowed values: 5.6, 7.0, 7.1, 7.2, 7.3)"
+	echo "-w <webroot>: set the path to the webroot directory (default: $PWD)"
 	exit 1;
 }
 
@@ -35,7 +37,7 @@ then
 fi
 
 # get options
-while getopts ":d:h:m:p:v:" x; do
+while getopts ":d:h:m:p:v:w:" x; do
     case "${x}" in
         d)
             d=${OPTARG}
@@ -52,6 +54,9 @@ while getopts ":d:h:m:p:v:" x; do
     	v)  
             v=${OPTARG}
 	       ;;
+    	w)  
+            w=${OPTARG}
+	       ;;
         *)
             usage
             ;;
@@ -65,6 +70,7 @@ port=80
 moodledata=$PWD/moodledata
 db_host=127.0.0.1
 php=7.3
+webroot=$PWD
 
 # default values may be overridden in a /etc/moodlehost.conf file
 if [ -f /etc/moodlehost.conf ]
@@ -93,29 +99,50 @@ then
 	php=$v
 fi
 
+if [ "$w" != "" ]
+then
+	webroot=$w
+fi
+
 dockername="moodlehost-${port}"
 
 
 if [ "$1" == "start" ]
 then
+	mkdir ${moodledata}
+	if [ ! -d $moodledata ]
+	then
+		echo "ERROR! Cannot create $moodledata directory - aborting!"
+		exit 1
+	fi
+	chmod -R 777 $moodledata
+
 	docker rm -f $dockername >/dev/null 2>/dev/null
 	docker run -d -p ${port}:80 \
 		--name $dockername \
-		-v $PWD:/var/www/html \
+		-v ${webroot}:/var/www/html \
 		-v ${moodledata}:/var/www/moodledata \
 		--add-host db_host:${db_host} \
-	moodlehq/moodle-php-apache:${php}
-	echo "==> $dockername with PHP version $php (re-)started on port $port using $PWD as web root"
+	qmulits/moodlehost:${php}
+	echo "==> $dockername with PHP version $php (re-)started on port $port using ${webroot} as web root"
 fi
 
 if [ "$1" == "stop" ]
 then
 	docker rm -f $dockername >/dev/null 2>/dev/null
-	echo "==> $dockername stopped and removed!"
+	echo "==> Container $dockername stopped and removed!"
 fi
 
 if [ "$1" == "purge" ]
 then
 	rm -rf ${moodledata}
+	mkdir ${moodledata}
+	if [ ! -d $moodledata ]
+	then
+		echo "ERROR! Cannot create $moodledata directory - aborting!"
+		exit 1
+	fi
+	chmod -R 777 $moodledata
+
 	echo "==> $dockername: moodledata purged"
 fi
